
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt .
RUN apt-get update && \
    apt-get install -y libpq-dev gcc && \
    pip install --no-cache-dir -r requirements.txt && \
    apt-get purge -y libpq-dev gcc && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*
COPY app.py .
EXPOSE 8000
CMD ["python", "app.py"]